name: update
on:
  # push:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 6,18 * * *"
jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/theeconomist/the-economist-war-fire-model:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGE_ACCESS_TOKEN }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with: # This is so the Pipe loads the LFS-tracked files
          lfs: true  

      - name: Run R script
        run: |
          source('scripts/000-autoupdater.R')
        shell: Rscript {0}

      # - name: Commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git commit --allow-empty -m "Data auto-update" -a

      # - name: Push changes
      #   uses: ad-m/github-push-action@8407731efefc0d8f72af254c74276b7a90be36e1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}